<div class="conteneur_link_info">
	<div class="link_info paiement_secur">
		<a href="#"><i class="fa fa-lock"></i>PAIEMENT SECURISE</a>
	</div>
	<div class="link_info livraison_rapide">
		<a href="#"><i class="fa fa-truck"></i>LIVRAISON RAPIDE</a>
	</div>
	<div class="link_info satisfait">
		<a href="#"><i class="fa fa-frown-o"></i></i>100% SATISFAIT</a>
	</div>
	<div class="link_info site_off_diet">
		<a href="#"><i class="fa fa-linux"></i>SITE OFFICIEL DIETIMEAL</a>
	</div>
</div>