<?php 
 ?>

<ul class="bxslider">
	<li><img src="<?php echo $this->getSkinURL(); ?>/images/perfect-body-1.jpg" /></li>
	<li><img src="<?php echo $this->getSkinURL(); ?>/images/perfect-body-2.jpg" /></li>
	<li><img src="<?php echo $this->getSkinURL(); ?>/images/perfect-body-3.jpg" /></li>
<!-- 	<?php 
		foreach ($this->getCollectionDeSlide() as $item) 
		{
			?>
				<li><img src="<?php echo $this->getSkinURL(); ?>/images/<?php echo $item->getData('image'); ?>" /></li>
			<?php
		}
	?>	 -->	

</ul>